project_name: mattermost-log-scrubber

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: mattermost-log-scrubber
    main: ./main.go

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"
  name_template: "Release {{ .Tag }}"
  header: |
    ## Mattermost Log Scrubber {{ .Tag }}
    
    This release includes cross-platform binaries for Linux, macOS, and Windows.
    
    ### Features
    - Privacy-focused log scrubbing with 3 configurable levels
    - Consistent user mapping for data utility
    - JSON field order preservation
    - IP address and UID masking options
    
    ### Usage
    ```bash
    ./mattermost-log-scrubber -i input.log -l 2 -o output.log
    ```